{
  try {
    op.onExecutionFailure(e);
  }
 catch (  Throwable t) {
    getLogger().warning("While calling operation.onFailure(). op: " + op,t);
  }
}
