{
  Exception ex=new Exception();
  future.complete(ex);
  Future joinFuture=spawn(new Callable<Object>(){
    @Override public Object call() throws Exception {
      return future.join();
    }
  }
);
  assertCompletesEventually(joinFuture);
  try {
    joinFuture.get();
    fail();
  }
 catch (  ExecutionException e) {
    HazelcastException hzEx=assertInstanceOf(HazelcastException.class,e.getCause());
    assertSame(ex,hzEx.getCause());
  }
}
