{
  ExecutionCallback callback=mock(ExecutionCallback.class);
  delegateThrowException=true;
  delegateFuture.run();
  outerFuture.andThen(callback);
  try {
    outerFuture.get();
    fail();
  }
 catch (  Throwable t) {
    assertEquals("Exception in execution",t.getCause().getMessage());
  }
  verify(callback,times(0)).onResponse(any(Throwable.class));
  verify(callback,times(1)).onFailure(any(Throwable.class));
}
