{
  ExecutionCallback<String> callback=getStringExecutionCallback();
  delegateThrowException=true;
  delegateFuture.run();
  outerFuture.andThen(callback);
  try {
    outerFuture.get();
    fail();
  }
 catch (  Throwable t) {
    assertEquals("Exception in execution",t.getCause().getMessage());
  }
  verify(callback,times(0)).onResponse(any(String.class));
  verify(callback,times(1)).onFailure(any(Throwable.class));
  verifyZeroInteractions(callback);
}
